# Generated by Django 2.2.7 on 2019-12-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/pepe.jpg', upload_to='blog'),
        ),
    ]
